//package com.mubeen.screencast;
//import org.junit.Test;
//import static org.junit.Assert.*;
//
///*
// * This Java source file was auto generated by running 'gradle init --type java-library'
// * by 'mubeen' at '10/2/16 7:36 PM' with Gradle 2.11
// *
// * @author mubeen, @date 10/2/16 7:36 PM
// */
//public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
//}
